message1 = Greeting.create(message: "Hi, what's up ?")
message2 = Greeting.create(message: "Hi, how is it going ?")
message3 = Greeting.create(message: "Hi there, July!")
message4 = Greeting.create(message: "Welcome, Marco!")
message5 = Greeting.create(message: "Greetings, samy!")